export const membershipTiers = [
  { label: "Ordinary", value: "ordinary", price: 500 },
  { label: "Bronze", value: "bronze", price: 2000 },
  { label: "Silver", value: "silver", price: 5000 },
  { label: "Gold", value: "gold", price: 10000 },
];

export const cities = [
  { label: "Baringo", value: "baringo" },
  { label: "Bomet", value: "bomet" },
  { label: "Bungoma", value: "bungoma" },
  { label: "Busia", value: "busia" },
  { label: "Elgeyo-Marakwet", value: "elgeyo-marakwet" },
  { label: "Embu", value: "embu" },
  { label: "Garissa", value: "garissa" },
  { label: "Homa Bay", value: "homa-bay" },
  { label: "Isiolo", value: "isiolo" },
  { label: "Kajiado", value: "kajiado" },
  { label: "Kakamega", value: "kakamega" },
  { label: "Kericho", value: "kericho" },
  { label: "Kiambu", value: "kiambu" },
  { label: "Kilifi", value: "kilifi" },
  { label: "Kirinyaga", value: "kirinyaga" },
  { label: "Kisii", value: "kisii" },
  { label: "Kisumu", value: "kisumu" },
  { label: "Kitui", value: "kitui" },
  { label: "Kwale", value: "kwale" },
  { label: "Laikipia", value: "laikipia" },
  { label: "Lamu", value: "lamu" },
  { label: "Machakos", value: "machakos" },
  { label: "Makueni", value: "makueni" },
  { label: "Mandera", value: "mandera" },
  { label: "Marsabit", value: "marsabit" },
  { label: "Meru", value: "meru" },
  { label: "Migori", value: "migori" },
  { label: "Mombasa", value: "mombasa" },
  { label: "Murang'a", value: "muranga" },
  { label: "Nairobi", value: "nairobi" },
  { label: "Nakuru", value: "nakuru" },
  { label: "Nandi", value: "nandi" },
  { label: "Narok", value: "narok" },
  { label: "Nyamira", value: "nyamira" },
  { label: "Nyandarua", value: "nyandarua" },
  { label: "Nyeri", value: "nyeri" },
  { label: "Samburu", value: "samburu" },
  { label: "Siaya", value: "siaya" },
  { label: "Taita-Taveta", value: "taita-taveta" },
  { label: "Tana River", value: "tana-river" },
  { label: "Tharaka-Nithi", value: "tharaka-nithi" },
  { label: "Trans Nzoia", value: "trans-nzoia" },
  { label: "Turkana", value: "turkana" },
  { label: "Uasin Gishu", value: "uasin-gishu" },
  { label: "Vihiga", value: "vihiga" },
  { label: "Wajir", value: "wajir" },
  { label: "West Pokot", value: "west-pokot" },
];

export const features = {
  ordinary: [
    "Membership included",
    "Official membership card",
    "Dedicated member entrance (faster entry) ",
  ],
  bronze: [
    "Membership included",
    "10% discount on match tickets",
    "Official membership card",
    "5% discount on merchandise",
    "Dedicated member entrance (faster entry) ",
    "Member-only pre-sale access to big matches",
  ],
  silver: [
    "Membership included",
    "Annual pass to ordinary stand for all home matches",
    "Official membership card",
    "Opportunity to upgrade to VIP stand during games",
    "Dedicated member entrance (faster entry) ",
    "Member-only pre-sale access to limited edition merchandise",
    "10% discount on merchandise",
  ],
  gold: [
    "Membership included",
    "Annual pass to VIP stand for all home matches",
    "Premium membership card",
    "Guaranteed big match access",
    "VIP entrance gate + reserved parking + bumper sticker",
    "Member-only pre-sale access to limited edition merchandise",
    "20% merchandise discount",
    "Access to player meet & greets and special events",
  ],
};
