export const mockMatches = [
    {
      id: '1',
      homeTeam: 'Murang\'a Seals',
      awayTeam: 'Nairobi City Stars',
      date: '2025-01-15T15:00:00',
      venue: 'Murang\'a Stadium',
      competition: 'League',
      ticketStatus: 'Available',
      isHome: true,
      isDerby: false,
      isFinal: false,
      result: null,
      attended: false,
      highlights: null,
    },
    {
      id: '2',
      homeTeam: 'Gor Mahia',
      awayTeam: 'Murang\'a Seals',
      date: '2025-02-01T14:30:00',
      venue: 'Kasarani Stadium',
      competition: 'Cup',
      ticketStatus: 'Sold Out',
      isHome: false,
      isDerby: true,
      isFinal: false,
      result: null,
      attended: false,
      highlights: null,
    },
    {
      id: '3',
      homeTeam: 'Murang\'a Seals',
      awayTeam: 'AFC Leopards',
      date: '2025-02-15T16:00:00',
      venue: 'Murang\'a Stadium',
      competition: 'League',
      ticketStatus: 'Booked',
      isHome: true,
      isDerby: false,
      isFinal: false,
      result: null,
      attended: false,
      highlights: null,
    },
    {
      id: '4',
      homeTeam: 'Murang\'a Seals',
      awayTeam: 'Tusker FC',
      date: '2024-12-20T15:00:00',
      venue: 'Murang\'a Stadium',
      competition: 'League',
      ticketStatus: 'Completed',
      isHome: true,
      isDerby: false,
      isFinal: false,
      result: '2-1',
      attended: true,
      highlights: 'https://example.com/highlights/match4',
    },
    {
      id: '5',
      homeTeam: 'Bandari FC',
      awayTeam: 'Murang\'a Seals',
      date: '2024-12-10T14:00:00',
      venue: 'Mbaraki Sports Club',
      competition: 'Cup',
      ticketStatus: 'Completed',
      isHome: false,
      isDerby: false,
      isFinal: false,
      result: '0-3',
      attended: false,
      highlights: 'https://example.com/highlights/match5',
    },
  ];
  
  