export const mockTickets = [
    {
      id: '1',
      matchName: 'Murang\'a Seals vs Nairobi City Stars',
      date: '2025-01-15T15:00:00',
      kickoff:'15:00:00',
      venue: 'Murang\'a Stadium',
      status: 'Valid',
      section: 'A',
      row: '10',
      seat: '5',
      thumbnail: 'https://www.murangaseal.com/assets/logo-a25ccce319b09f73006dc94d71887dbd26f5afeec59c2fa5dca6afaf101fe82c.png',
      matchPreview: 'A thrilling match between local rivals...',
      keyPlayers: 'John Doe (Murang\'a Seals), Jane Smith (Nairobi City Stars)',
      weatherForecast: 'Sunny, 22°C',
      ticketType: 'VIP',
      transactionId: 'TRX123456',
    },
    {
      id: '2',
      matchName: 'Murang\'a Seals vs Gor Mahia',
      date: '2025-02-01T14:30:00',
      kickoff:'15:00:00',
      venue: 'Kasarani Stadium',
      status: 'Pending',
      section: 'B',
      row: '5',
      seat: '12',
      thumbnail: 'https://www.murangaseal.com/assets/logo-a25ccce319b09f73006dc94d71887dbd26f5afeec59c2fa5dca6afaf101fe82c.png',
      matchPreview: 'An exciting face-off between...',
      keyPlayers: 'Alex Johnson (Murang\'a Seals), Mike Brown (Gor Mahia)',
      weatherForecast: 'Partly cloudy, 24°C',
      ticketType: 'Regular',
      transactionId: 'TRX789012',
    },
    {
      id: '3',
      matchName: 'Murang\'a Seals vs AFC Leopards',
      date: '2025-02-15T16:00:00',
      kickoff:'15:00:00',
      venue: 'Nyayo National Stadium',
      status: 'Used',
      section: 'C',
      row: '8',
      seat: '20',
      thumbnail: 'https://www.murangaseal.com/assets/logo-a25ccce319b09f73006dc94d71887dbd26f5afeec59c2fa5dca6afaf101fe82c.png',
      matchPreview: 'A crucial match that could decide...',
      keyPlayers: 'Sarah Lee (Murang\'a Seals), Tom Wilson (AFC Leopards)',
      weatherForecast: 'Clear skies, 26°C',
      ticketType: 'Family Area',
      transactionId: 'TRX345678',
    },
  ];
  
  